(in-package #:ui)

(include "ui.h")

(ctype size-t "size_t")

(constant (default-miter-limit "uiDrawDefaultMiterLimit") :type double-float)

(cenum (%for-each :base-type :unsigned-int)
	((:continue "uiForEachContinue"))
	((:stop "uiForEachStop")))

(cenum (%attribute-type :base-type :unsigned-int)
  ((:family "uiAttributeTypeFamily"))
  ((:size "uiAttributeTypeSize"))
  ((:weight "uiAttributeTypeWeight"))
  ((:italic "uiAttributeTypeItalic"))
  ((:stretch "uiAttributeTypeStretch"))
  ((:color "uiAttributeTypeColor"))
  ((:background "uiAttributeTypeBackground"))
  ((:underline "uiAttributeTypeUnderline"))
  ((:underline-color "uiAttributeTypeUnderlineColor"))
  ((:features "uiAttributeTypeFeatures")))

(cenum (%window-resize-edge :base-type :unsigned-int)
	((:left "uiWindowResizeEdgeLeft"))
	((:top "uiWindowResizeEdgeTop"))
	((:right "uiWindowResizeEdgeRight"))
	((:bottom "uiWindowResizeEdgeBottom"))
	((:top-left "uiWindowResizeEdgeTopLeft"))
	((:top-right "uiWindowResizeEdgeTopRight"))
	((:bottom-left "uiWindowResizeEdgeBottomLeft"))
	((:bottom-right "uiWindowResizeEdgeBottomRight")))

(cenum (%draw-brush-type :base-type :unsigned-int)
  ((:solid "uiDrawBrushTypeSolid"))
  ((:linear-gradient "uiDrawBrushTypeLinearGradient"))
  ((:radial-gradient "uiDrawBrushTypeRadialGradient"))
  ((:image "uiDrawBrushTypeImage")))

(cenum (%draw-line-cap :base-type :unsigned-int)
  ((:flat "uiDrawLineCapFlat"))
  ((:round "uiDrawLineCapRound"))
  ((:square "uiDrawLineCapSquare")))

(cenum (%draw-line-join :base-type :unsigned-int)
  ((:miter "uiDrawLineJoinMiter"))
  ((:round "uiDrawLineJoinRound"))
  ((:bevel "uiDrawLineJoinRound")))

(cenum (%draw-fill-mode :base-type :unsigned-int)
  ((:winding "uiDrawFillModeWinding"))
  ((:alternate "uiDrawFillModeAlternate")))

(cenum (%text-weight :base-type :unsigned-int)
  ((:minimum "uiTextWeightMinimum"))
  ((:thin "uiTextWeightThin"))
  ((:ultra-light "uiTextWeightUltraLight"))
  ((:light "uiTextWeightLight"))
  ((:book "uiTextWeightBook"))
  ((:normal "uiTextWeightNormal"))
  ((:medium "uiTextWeightMedium"))
  ((:semi-bold "uiTextWeightSemiBold"))
  ((:bold "uiTextWeightBold"))
  ((:ultra-bold "uiTextWeightUltraBold"))
  ((:heavy "uiTextWeightHeavy"))
  ((:ultra-heavy "uiTextWeightUltraHeavy"))
  ((:maximum "uiTextWeightMaximum")))

(cenum (%text-italic :base-type :unsigned-int)
  ((:normal "uiTextItalicNormal"))
  ((:oblique "uiTextItalicOblique"))
  ((:italic "uiTextItalicItalic")))

(cenum (%text-stretch :base-type :unsigned-int)
  ((:ultra-condensed "uiTextStretchUltraCondensed"))
  ((:extra-condensed "uiTextStretchExtraCondensed"))
  ((:condensed "uiTextStretchCondensed"))
  ((:semi-condensed "uiTextStretchSemiCondensed"))
  ((:normal "uiTextStretchNormal"))
  ((:semi-expanded "uiTextStretchSemiExpanded"))
  ((:expanded "uiTextStretchExpanded"))
  ((:extra-expanded "uiTextStretchExtraExpanded"))
  ((:ultra-expanded "uiTextStretchUltraExpanded")))

(cenum (%underline :base-type :unsigned-int)
  ((:none "uiUnderlineNone"))
  ((:single "uiUnderlineSingle"))
  ((:double "uiUnderlineDouble"))
  ((:suggestion "uiUnderlineSuggestion")))

(cenum (%underline-color :base-type :unsigned-int)
  ((:custom "uiUnderlineColorCustom"))
  ((:spelling "uiUnderlineColorCustom"))
  ((:grammar "uiUnderlineColorGrammar"))
  ((:auxiliary "uiUnderlineColorAuxiliary")))

(cenum (%draw-text-align :base-type :unsigned-int)
  ((:left "uiDrawTextAlignLeft"))
  ((:center "uiDrawTextAlignCenter"))
  ((:right "uiDrawTextAlignRight")))

(cenum (%ext-key :base-type :unsigned-int)
  ((:none "0"))
  ((:escape "uiExtKeyEscape"))
  ((:insert "uiExtKeyInsert"))
  ((:delete "uiExtKeyDelete"))
  ((:home "uiExtKeyHome"))
  ((:end "uiExtKeyEnd"))
  ((:page-up "uiExtKeyPageUp"))
  ((:page-down "uiExtKeyPageDown"))
  ((:up "uiExtKeyUp"))
  ((:down "uiExtKeyDown"))
  ((:left "uiExtKeyLeft"))
  ((:right "uiExtKeyRight"))
  ((:f1 "uiExtKeyF1"))
  ((:f2 "uiExtKeyF2"))
  ((:f3 "uiExtKeyF3"))
  ((:f4 "uiExtKeyF4"))
  ((:f5 "uiExtKeyF5"))
  ((:f6 "uiExtKeyF6"))
  ((:f7 "uiExtKeyF7"))
  ((:f8 "uiExtKeyF8"))
  ((:f9 "uiExtKeyF9"))
  ((:f10 "uiExtKeyF10"))
  ((:f11 "uiExtKeyF11"))
  ((:f12 "uiExtKeyF12"))
  ((:n0 "uiExtKeyN0"))
  ((:n1 "uiExtKeyN1"))
  ((:n2 "uiExtKeyN2"))
  ((:n3 "uiExtKeyN3"))
  ((:n4 "uiExtKeyN4"))
  ((:n5 "uiExtKeyN5"))
  ((:n6 "uiExtKeyN6"))
  ((:n7 "uiExtKeyN7"))
  ((:n8 "uiExtKeyN8"))
  ((:n9 "uiExtKeyN9"))
  ((:n-dot "uiExtKeyNDot"))
  ((:n-enter "uiExtKeyNEnter"))
  ((:n-add "uiExtKeyNAdd"))
  ((:n-subtract "uiExtKeyNSubtract"))
  ((:n-multiply "uiExtKeyNMultiply"))
  ((:n-divide "uiExtKeyNDivide")))

(cenum (%align :base-type :unsigned-int)
  ((:fill "uiAlignFill"))
  ((:start "uiAlignStart"))
  ((:center "uiAlignCenter"))
  ((:end "uiAlignEnd")))

(cenum (%at :base-type :unsigned-int)
  ((:leading "uiAtLeading"))
  ((:top "uiAtTop"))
  ((:trailing "uiAtTrailing"))
  ((:bottom "uiAtBottom")))

(cenum (%table-value-type :base-type :unsigned-int)
  ((:string "uiTableValueTypeString"))
  ((:image "uiTableValueTypeImage"))
  ((:int "uiTableValueTypeInt"))
  ((:color "uiTableValueTypeColor")))

; (bitfield (%modifiers :base-type :unsigned-int)
; 	((:ctrl "uiModifierCtrl"))
; 	((:alt "uiModifierAlt"))
; 	((:shift "uiModifierShift"))
; 	((:super "uiModifierSuper")))
